#!/bin/bash

if [ -d files/authorized_keys ]; then
  mkdir -m 700 -p /root/.ssh
  find files/authorized_keys -iname "*.pub" -exec cat {} + >/root/.ssh/authorized_keys
  chown -R root:root /root/.ssh
  chmod 600 /root/.ssh/authorized_keys
fi
